//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Act2", Namespace="http://schemas.datacontract.org/2004/07/MainAPIWCF")]
    [System.SerializableAttribute()]
    public partial class Act2 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CaseTypeField;
        
        private string CreditorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExitDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExitReasonField;
        
        private string ImportDateStringField;
        
        private string RefNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.Deposit> depositsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CaseType {
            get {
                return this.CaseTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CaseTypeField, value) != true)) {
                    this.CaseTypeField = value;
                    this.RaisePropertyChanged("CaseType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Creditor {
            get {
                return this.CreditorField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditorField, value) != true)) {
                    this.CreditorField = value;
                    this.RaisePropertyChanged("Creditor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExitDate {
            get {
                return this.ExitDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ExitDateField, value) != true)) {
                    this.ExitDateField = value;
                    this.RaisePropertyChanged("ExitDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExitReason {
            get {
                return this.ExitReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ExitReasonField, value) != true)) {
                    this.ExitReasonField = value;
                    this.RaisePropertyChanged("ExitReason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ImportDateString {
            get {
                return this.ImportDateStringField;
            }
            set {
                if ((object.ReferenceEquals(this.ImportDateStringField, value) != true)) {
                    this.ImportDateStringField = value;
                    this.RaisePropertyChanged("ImportDateString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RefNo {
            get {
                return this.RefNoField;
            }
            set {
                if ((object.ReferenceEquals(this.RefNoField, value) != true)) {
                    this.RefNoField = value;
                    this.RaisePropertyChanged("RefNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.Deposit> deposits {
            get {
                return this.depositsField;
            }
            set {
                if ((object.ReferenceEquals(this.depositsField, value) != true)) {
                    this.depositsField = value;
                    this.RaisePropertyChanged("deposits");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Deposit", Namespace="http://schemas.datacontract.org/2004/07/MainAPIWCF")]
    [System.SerializableAttribute()]
    public partial class Deposit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DepositDateField;
        
        private int DepositIdField;
        
        private decimal DepositedAmountField;
        
        private string ImportDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.CostDeposit> costDepositsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DepositDate {
            get {
                return this.DepositDateField;
            }
            set {
                if ((object.ReferenceEquals(this.DepositDateField, value) != true)) {
                    this.DepositDateField = value;
                    this.RaisePropertyChanged("DepositDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DepositId {
            get {
                return this.DepositIdField;
            }
            set {
                if ((this.DepositIdField.Equals(value) != true)) {
                    this.DepositIdField = value;
                    this.RaisePropertyChanged("DepositId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal DepositedAmount {
            get {
                return this.DepositedAmountField;
            }
            set {
                if ((this.DepositedAmountField.Equals(value) != true)) {
                    this.DepositedAmountField = value;
                    this.RaisePropertyChanged("DepositedAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ImportDate {
            get {
                return this.ImportDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ImportDateField, value) != true)) {
                    this.ImportDateField = value;
                    this.RaisePropertyChanged("ImportDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.CostDeposit> costDeposits {
            get {
                return this.costDepositsField;
            }
            set {
                if ((object.ReferenceEquals(this.costDepositsField, value) != true)) {
                    this.costDepositsField = value;
                    this.RaisePropertyChanged("costDeposits");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CostDeposit", Namespace="http://schemas.datacontract.org/2004/07/MainAPIWCF")]
    [System.SerializableAttribute()]
    public partial class CostDeposit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal AmountToClientField;
        
        private decimal AmountToDebtCollectorField;
        
        private int CostTypeIdField;
        
        private string CostTypeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal AmountToClient {
            get {
                return this.AmountToClientField;
            }
            set {
                if ((this.AmountToClientField.Equals(value) != true)) {
                    this.AmountToClientField = value;
                    this.RaisePropertyChanged("AmountToClient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal AmountToDebtCollector {
            get {
                return this.AmountToDebtCollectorField;
            }
            set {
                if ((this.AmountToDebtCollectorField.Equals(value) != true)) {
                    this.AmountToDebtCollectorField = value;
                    this.RaisePropertyChanged("AmountToDebtCollector");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CostTypeId {
            get {
                return this.CostTypeIdField;
            }
            set {
                if ((this.CostTypeIdField.Equals(value) != true)) {
                    this.CostTypeIdField = value;
                    this.RaisePropertyChanged("CostTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CostTypeName {
            get {
                return this.CostTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CostTypeNameField, value) != true)) {
                    this.CostTypeNameField = value;
                    this.RaisePropertyChanged("CostTypeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IncomingDeposit", Namespace="http://schemas.datacontract.org/2004/07/MainAPIWCF")]
    [System.SerializableAttribute()]
    public partial class IncomingDeposit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DebtorNameField;
        
        private string DepositDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DebtorName {
            get {
                return this.DebtorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DebtorNameField, value) != true)) {
                    this.DebtorNameField = value;
                    this.RaisePropertyChanged("DebtorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DepositDate {
            get {
                return this.DepositDateField;
            }
            set {
                if ((object.ReferenceEquals(this.DepositDateField, value) != true)) {
                    this.DepositDateField = value;
                    this.RaisePropertyChanged("DepositDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusUpdate", Namespace="http://schemas.datacontract.org/2004/07/MainAPIWCF")]
    [System.SerializableAttribute()]
    public partial class StatusUpdate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CaseTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RefNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimestampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CaseTypeId {
            get {
                return this.CaseTypeIdField;
            }
            set {
                if ((this.CaseTypeIdField.Equals(value) != true)) {
                    this.CaseTypeIdField = value;
                    this.RaisePropertyChanged("CaseTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewStatus {
            get {
                return this.NewStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.NewStatusField, value) != true)) {
                    this.NewStatusField = value;
                    this.RaisePropertyChanged("NewStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefNo {
            get {
                return this.RefNoField;
            }
            set {
                if ((object.ReferenceEquals(this.RefNoField, value) != true)) {
                    this.RefNoField = value;
                    this.RaisePropertyChanged("RefNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((object.ReferenceEquals(this.TimestampField, value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Act", Namespace="http://schemas.datacontract.org/2004/07/DBTool")]
    [System.SerializableAttribute()]
    public partial class Act : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string caseOriginalCreditorField;
        
        private string caseReferenceIdField;
        
        private int caseTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.Debtor> debtorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.Debt> debtsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> decisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.ActExtraFields extraFieldsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string caseOriginalCreditor {
            get {
                return this.caseOriginalCreditorField;
            }
            set {
                if ((object.ReferenceEquals(this.caseOriginalCreditorField, value) != true)) {
                    this.caseOriginalCreditorField = value;
                    this.RaisePropertyChanged("caseOriginalCreditor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string caseReferenceId {
            get {
                return this.caseReferenceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.caseReferenceIdField, value) != true)) {
                    this.caseReferenceIdField = value;
                    this.RaisePropertyChanged("caseReferenceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int caseTypeId {
            get {
                return this.caseTypeIdField;
            }
            set {
                if ((this.caseTypeIdField.Equals(value) != true)) {
                    this.caseTypeIdField = value;
                    this.RaisePropertyChanged("caseTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.Debtor> debtors {
            get {
                return this.debtorsField;
            }
            set {
                if ((object.ReferenceEquals(this.debtorsField, value) != true)) {
                    this.debtorsField = value;
                    this.RaisePropertyChanged("debtors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.Debt> debts {
            get {
                return this.debtsField;
            }
            set {
                if ((object.ReferenceEquals(this.debtsField, value) != true)) {
                    this.debtsField = value;
                    this.RaisePropertyChanged("debts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> decision {
            get {
                return this.decisionField;
            }
            set {
                if ((this.decisionField.Equals(value) != true)) {
                    this.decisionField = value;
                    this.RaisePropertyChanged("decision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.ActExtraFields extraFields {
            get {
                return this.extraFieldsField;
            }
            set {
                if ((object.ReferenceEquals(this.extraFieldsField, value) != true)) {
                    this.extraFieldsField = value;
                    this.RaisePropertyChanged("extraFields");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActExtraFields", Namespace="http://schemas.datacontract.org/2004/07/DBTool")]
    [System.SerializableAttribute()]
    public partial class ActExtraFields : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> ExtraFieldsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> ExtraFieldsDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> ExtraFields {
            get {
                return this.ExtraFieldsField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtraFieldsField, value) != true)) {
                    this.ExtraFieldsField = value;
                    this.RaisePropertyChanged("ExtraFields");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> ExtraFieldsData {
            get {
                return this.ExtraFieldsDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtraFieldsDataField, value) != true)) {
                    this.ExtraFieldsDataField = value;
                    this.RaisePropertyChanged("ExtraFieldsData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Debtor", Namespace="http://schemas.datacontract.org/2004/07/DBTool")]
    [System.SerializableAttribute()]
    public partial class Debtor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string attentionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string birthdayField;
        
        private string cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string coAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string countryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cprField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cvrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneField;
        
        private string postalCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string attention {
            get {
                return this.attentionField;
            }
            set {
                if ((object.ReferenceEquals(this.attentionField, value) != true)) {
                    this.attentionField = value;
                    this.RaisePropertyChanged("attention");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string birthday {
            get {
                return this.birthdayField;
            }
            set {
                if ((object.ReferenceEquals(this.birthdayField, value) != true)) {
                    this.birthdayField = value;
                    this.RaisePropertyChanged("birthday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string coAddress {
            get {
                return this.coAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.coAddressField, value) != true)) {
                    this.coAddressField = value;
                    this.RaisePropertyChanged("coAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string countryCode {
            get {
                return this.countryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.countryCodeField, value) != true)) {
                    this.countryCodeField = value;
                    this.RaisePropertyChanged("countryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cpr {
            get {
                return this.cprField;
            }
            set {
                if ((object.ReferenceEquals(this.cprField, value) != true)) {
                    this.cprField = value;
                    this.RaisePropertyChanged("cpr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cvr {
            get {
                return this.cvrField;
            }
            set {
                if ((object.ReferenceEquals(this.cvrField, value) != true)) {
                    this.cvrField = value;
                    this.RaisePropertyChanged("cvr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneField, value) != true)) {
                    this.phoneField = value;
                    this.RaisePropertyChanged("phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string postalCode {
            get {
                return this.postalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.postalCodeField, value) != true)) {
                    this.postalCodeField = value;
                    this.RaisePropertyChanged("postalCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Debt", Namespace="http://schemas.datacontract.org/2004/07/DBTool")]
    [System.SerializableAttribute()]
    public partial class Debt : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> compensationFeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.DebtExtraFields extraFieldsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> feeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> interestRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string interestStartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string invoiceDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string invoiceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> otherFeesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal principalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> compensationFee {
            get {
                return this.compensationFeeField;
            }
            set {
                if ((this.compensationFeeField.Equals(value) != true)) {
                    this.compensationFeeField = value;
                    this.RaisePropertyChanged("compensationFee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dueDate {
            get {
                return this.dueDateField;
            }
            set {
                if ((object.ReferenceEquals(this.dueDateField, value) != true)) {
                    this.dueDateField = value;
                    this.RaisePropertyChanged("dueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.DebtExtraFields extraFields {
            get {
                return this.extraFieldsField;
            }
            set {
                if ((object.ReferenceEquals(this.extraFieldsField, value) != true)) {
                    this.extraFieldsField = value;
                    this.RaisePropertyChanged("extraFields");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> fee {
            get {
                return this.feeField;
            }
            set {
                if ((this.feeField.Equals(value) != true)) {
                    this.feeField = value;
                    this.RaisePropertyChanged("fee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> interestRate {
            get {
                return this.interestRateField;
            }
            set {
                if ((this.interestRateField.Equals(value) != true)) {
                    this.interestRateField = value;
                    this.RaisePropertyChanged("interestRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string interestStartDate {
            get {
                return this.interestStartDateField;
            }
            set {
                if ((object.ReferenceEquals(this.interestStartDateField, value) != true)) {
                    this.interestStartDateField = value;
                    this.RaisePropertyChanged("interestStartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string invoiceDate {
            get {
                return this.invoiceDateField;
            }
            set {
                if ((object.ReferenceEquals(this.invoiceDateField, value) != true)) {
                    this.invoiceDateField = value;
                    this.RaisePropertyChanged("invoiceDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string invoiceId {
            get {
                return this.invoiceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.invoiceIdField, value) != true)) {
                    this.invoiceIdField = value;
                    this.RaisePropertyChanged("invoiceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> otherFees {
            get {
                return this.otherFeesField;
            }
            set {
                if ((this.otherFeesField.Equals(value) != true)) {
                    this.otherFeesField = value;
                    this.RaisePropertyChanged("otherFees");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal principal {
            get {
                return this.principalField;
            }
            set {
                if ((this.principalField.Equals(value) != true)) {
                    this.principalField = value;
                    this.RaisePropertyChanged("principal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DebtExtraFields", Namespace="http://schemas.datacontract.org/2004/07/DBTool")]
    [System.SerializableAttribute()]
    public partial class DebtExtraFields : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> ExtraFieldsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> ExtraFieldsDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> ExtraFields {
            get {
                return this.ExtraFieldsField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtraFieldsField, value) != true)) {
                    this.ExtraFieldsField = value;
                    this.RaisePropertyChanged("ExtraFields");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> ExtraFieldsData {
            get {
                return this.ExtraFieldsDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtraFieldsDataField, value) != true)) {
                    this.ExtraFieldsDataField = value;
                    this.RaisePropertyChanged("ExtraFieldsData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentSpecificationItem", Namespace="http://schemas.datacontract.org/2004/07/MainAPIWCF")]
    [System.SerializableAttribute()]
    public partial class PaymentSpecificationItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal AmountField;
        
        private string CaseTypeField;
        
        private string CostField;
        
        private string DepositDateField;
        
        private int DepositIdField;
        
        private string ImportTimeField;
        
        private string RefNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CaseType {
            get {
                return this.CaseTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CaseTypeField, value) != true)) {
                    this.CaseTypeField = value;
                    this.RaisePropertyChanged("CaseType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Cost {
            get {
                return this.CostField;
            }
            set {
                if ((object.ReferenceEquals(this.CostField, value) != true)) {
                    this.CostField = value;
                    this.RaisePropertyChanged("Cost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DepositDate {
            get {
                return this.DepositDateField;
            }
            set {
                if ((object.ReferenceEquals(this.DepositDateField, value) != true)) {
                    this.DepositDateField = value;
                    this.RaisePropertyChanged("DepositDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DepositId {
            get {
                return this.DepositIdField;
            }
            set {
                if ((this.DepositIdField.Equals(value) != true)) {
                    this.DepositIdField = value;
                    this.RaisePropertyChanged("DepositId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ImportTime {
            get {
                return this.ImportTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImportTimeField, value) != true)) {
                    this.ImportTimeField = value;
                    this.RaisePropertyChanged("ImportTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RefNo {
            get {
                return this.RefNoField;
            }
            set {
                if ((object.ReferenceEquals(this.RefNoField, value) != true)) {
                    this.RefNoField = value;
                    this.RaisePropertyChanged("RefNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExitReport", Namespace="http://schemas.datacontract.org/2004/07/MainAPIWCF")]
    [System.SerializableAttribute()]
    public partial class ExitReport : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ActIdField;
        
        private string CaseTypeField;
        
        private string CreditorField;
        
        private int CreditorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExitTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExitTimeStringField;
        
        private System.DateTime ImportDateField;
        
        private string ImportDateStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaidToField;
        
        private string RefNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ActId {
            get {
                return this.ActIdField;
            }
            set {
                if ((this.ActIdField.Equals(value) != true)) {
                    this.ActIdField = value;
                    this.RaisePropertyChanged("ActId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CaseType {
            get {
                return this.CaseTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CaseTypeField, value) != true)) {
                    this.CaseTypeField = value;
                    this.RaisePropertyChanged("CaseType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Creditor {
            get {
                return this.CreditorField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditorField, value) != true)) {
                    this.CreditorField = value;
                    this.RaisePropertyChanged("Creditor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CreditorId {
            get {
                return this.CreditorIdField;
            }
            set {
                if ((this.CreditorIdField.Equals(value) != true)) {
                    this.CreditorIdField = value;
                    this.RaisePropertyChanged("CreditorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Exit {
            get {
                return this.ExitField;
            }
            set {
                if ((object.ReferenceEquals(this.ExitField, value) != true)) {
                    this.ExitField = value;
                    this.RaisePropertyChanged("Exit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExitTime {
            get {
                return this.ExitTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExitTimeField, value) != true)) {
                    this.ExitTimeField = value;
                    this.RaisePropertyChanged("ExitTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExitTimeString {
            get {
                return this.ExitTimeStringField;
            }
            set {
                if ((object.ReferenceEquals(this.ExitTimeStringField, value) != true)) {
                    this.ExitTimeStringField = value;
                    this.RaisePropertyChanged("ExitTimeString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime ImportDate {
            get {
                return this.ImportDateField;
            }
            set {
                if ((this.ImportDateField.Equals(value) != true)) {
                    this.ImportDateField = value;
                    this.RaisePropertyChanged("ImportDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ImportDateString {
            get {
                return this.ImportDateStringField;
            }
            set {
                if ((object.ReferenceEquals(this.ImportDateStringField, value) != true)) {
                    this.ImportDateStringField = value;
                    this.RaisePropertyChanged("ImportDateString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaidTo {
            get {
                return this.PaidToField;
            }
            set {
                if ((object.ReferenceEquals(this.PaidToField, value) != true)) {
                    this.PaidToField = value;
                    this.RaisePropertyChanged("PaidTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RefNo {
            get {
                return this.RefNoField;
            }
            set {
                if ((object.ReferenceEquals(this.RefNoField, value) != true)) {
                    this.RefNoField = value;
                    this.RaisePropertyChanged("RefNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentPlanItem", Namespace="http://schemas.datacontract.org/2004/07/MainAPIWCF")]
    [System.SerializableAttribute()]
    public partial class PaymentPlanItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal AmountField;
        
        private string DateField;
        
        private decimal InterestField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Interest {
            get {
                return this.InterestField;
            }
            set {
                if ((this.InterestField.Equals(value) != true)) {
                    this.InterestField = value;
                    this.RaisePropertyChanged("Interest");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAction", Namespace="http://schemas.datacontract.org/2004/07/MainAPIWCF")]
    [System.SerializableAttribute()]
    public partial class UserAction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActionId {
            get {
                return this.ActionIdField;
            }
            set {
                if ((this.ActionIdField.Equals(value) != true)) {
                    this.ActionIdField = value;
                    this.RaisePropertyChanged("ActionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SystemOneSoapService.SystemOneSoapService")]
    public interface SystemOneSoapService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/TestConnectionGet", ReplyAction="http://tempuri.org/SystemOneSoapService/TestConnectionGetResponse")]
        void TestConnectionGet();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/TestConnectionGet", ReplyAction="http://tempuri.org/SystemOneSoapService/TestConnectionGetResponse")]
        System.Threading.Tasks.Task TestConnectionGetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/TestConnectionPost", ReplyAction="http://tempuri.org/SystemOneSoapService/TestConnectionPostResponse")]
        void TestConnectionPost();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/TestConnectionPost", ReplyAction="http://tempuri.org/SystemOneSoapService/TestConnectionPostResponse")]
        System.Threading.Tasks.Task TestConnectionPostAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/GetActs", ReplyAction="http://tempuri.org/SystemOneSoapService/GetActsResponse")]
        System.Collections.Generic.List<InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.Act2> GetActs(string token, int versionNumber, int caseTypeId, string startDateString, string endDateString, string refNosString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/GetActs", ReplyAction="http://tempuri.org/SystemOneSoapService/GetActsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.Act2>> GetActsAsync(string token, int versionNumber, int caseTypeId, string startDateString, string endDateString, string refNosString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/ExitAct", ReplyAction="http://tempuri.org/SystemOneSoapService/ExitActResponse")]
        void ExitAct(string token, int versionNumber, string caseReferenceId, string reason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/ExitAct", ReplyAction="http://tempuri.org/SystemOneSoapService/ExitActResponse")]
        System.Threading.Tasks.Task ExitActAsync(string token, int versionNumber, string caseReferenceId, string reason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/Deposit", ReplyAction="http://tempuri.org/SystemOneSoapService/DepositResponse")]
        void Deposit(string token, int versionNumber, string caseReferenceId, [System.ServiceModel.MessageParameterAttribute(Name="deposit")] InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.IncomingDeposit deposit1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/Deposit", ReplyAction="http://tempuri.org/SystemOneSoapService/DepositResponse")]
        System.Threading.Tasks.Task DepositAsync(string token, int versionNumber, string caseReferenceId, InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.IncomingDeposit deposit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/GetStatusUpdates", ReplyAction="http://tempuri.org/SystemOneSoapService/GetStatusUpdatesResponse")]
        System.Collections.Generic.List<InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.StatusUpdate> GetStatusUpdates(string token, string versionNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/GetStatusUpdates", ReplyAction="http://tempuri.org/SystemOneSoapService/GetStatusUpdatesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.StatusUpdate>> GetStatusUpdatesAsync(string token, string versionNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/ImportActDirect", ReplyAction="http://tempuri.org/SystemOneSoapService/ImportActDirectResponse")]
        void ImportActDirect(string token, int versionNumber, bool allDebtsBelongToAllDebtors, InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.Act actImport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/ImportActDirect", ReplyAction="http://tempuri.org/SystemOneSoapService/ImportActDirectResponse")]
        System.Threading.Tasks.Task ImportActDirectAsync(string token, int versionNumber, bool allDebtsBelongToAllDebtors, InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.Act actImport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/UpdateAct", ReplyAction="http://tempuri.org/SystemOneSoapService/UpdateActResponse")]
        void UpdateAct(string token, int versionNumber, string caseReferenceId, bool allDebtsBelongToAllDebtors, InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.Debt debtImport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/UpdateAct", ReplyAction="http://tempuri.org/SystemOneSoapService/UpdateActResponse")]
        System.Threading.Tasks.Task UpdateActAsync(string token, int versionNumber, string caseReferenceId, bool allDebtsBelongToAllDebtors, InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.Debt debtImport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/ImportAct", ReplyAction="http://tempuri.org/SystemOneSoapService/ImportActResponse")]
        void ImportAct(string token, int versionNumber, InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.Act actImport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/ImportAct", ReplyAction="http://tempuri.org/SystemOneSoapService/ImportActResponse")]
        System.Threading.Tasks.Task ImportActAsync(string token, int versionNumber, InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.Act actImport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/GetPaymentSpecification", ReplyAction="http://tempuri.org/SystemOneSoapService/GetPaymentSpecificationResponse")]
        System.Collections.Generic.List<InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.PaymentSpecificationItem> GetPaymentSpecification(string token, string versionNumber, string startTimeString, string endTimeString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/GetPaymentSpecification", ReplyAction="http://tempuri.org/SystemOneSoapService/GetPaymentSpecificationResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.PaymentSpecificationItem>> GetPaymentSpecificationAsync(string token, string versionNumber, string startTimeString, string endTimeString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/EndSupply", ReplyAction="http://tempuri.org/SystemOneSoapService/EndSupplyResponse")]
        void EndSupply(string token, int versionNumber, string caseReferenceId, string action, string reason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/EndSupply", ReplyAction="http://tempuri.org/SystemOneSoapService/EndSupplyResponse")]
        System.Threading.Tasks.Task EndSupplyAsync(string token, int versionNumber, string caseReferenceId, string action, string reason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/GetExitReport", ReplyAction="http://tempuri.org/SystemOneSoapService/GetExitReportResponse")]
        System.Collections.Generic.List<InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.ExitReport> GetExitReport(string token, int versionNumber, int caseTypeId, string startTimeString, string endTimeString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/GetExitReport", ReplyAction="http://tempuri.org/SystemOneSoapService/GetExitReportResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.ExitReport>> GetExitReportAsync(string token, int versionNumber, int caseTypeId, string startTimeString, string endTimeString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/CreatePaymentPlan", ReplyAction="http://tempuri.org/SystemOneSoapService/CreatePaymentPlanResponse")]
        System.Collections.Generic.List<InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.PaymentPlanItem> CreatePaymentPlan(string token, int versionNumber, int actId, int debtorId, string startTimeString, string amountString, string debtIdsString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/CreatePaymentPlan", ReplyAction="http://tempuri.org/SystemOneSoapService/CreatePaymentPlanResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.PaymentPlanItem>> CreatePaymentPlanAsync(string token, int versionNumber, int actId, int debtorId, string startTimeString, string amountString, string debtIdsString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/IsNotificationStoredProceduresStillRunnin" +
            "g", ReplyAction="http://tempuri.org/SystemOneSoapService/IsNotificationStoredProceduresStillRunnin" +
            "gResponse")]
        int IsNotificationStoredProceduresStillRunning();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/IsNotificationStoredProceduresStillRunnin" +
            "g", ReplyAction="http://tempuri.org/SystemOneSoapService/IsNotificationStoredProceduresStillRunnin" +
            "gResponse")]
        System.Threading.Tasks.Task<int> IsNotificationStoredProceduresStillRunningAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/GetActionsToday", ReplyAction="http://tempuri.org/SystemOneSoapService/GetActionsTodayResponse")]
        System.Collections.Generic.List<InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.UserAction> GetActionsToday();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/GetActionsToday", ReplyAction="http://tempuri.org/SystemOneSoapService/GetActionsTodayResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.UserAction>> GetActionsTodayAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/GetWNSChannelToken", ReplyAction="http://tempuri.org/SystemOneSoapService/GetWNSChannelTokenResponse")]
        string GetWNSChannelToken();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/GetWNSChannelToken", ReplyAction="http://tempuri.org/SystemOneSoapService/GetWNSChannelTokenResponse")]
        System.Threading.Tasks.Task<string> GetWNSChannelTokenAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/SetWNSChannelToken", ReplyAction="http://tempuri.org/SystemOneSoapService/SetWNSChannelTokenResponse")]
        void SetWNSChannelToken(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/SetWNSChannelToken", ReplyAction="http://tempuri.org/SystemOneSoapService/SetWNSChannelTokenResponse")]
        System.Threading.Tasks.Task SetWNSChannelTokenAsync(string token);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SystemOneSoapServiceChannel : InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.SystemOneSoapService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SystemOneSoapServiceClient : System.ServiceModel.ClientBase<InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.SystemOneSoapService>, InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.SystemOneSoapService {
        
        public SystemOneSoapServiceClient() {
        }
        
        public SystemOneSoapServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SystemOneSoapServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemOneSoapServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemOneSoapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void TestConnectionGet() {
            base.Channel.TestConnectionGet();
        }
        
        public System.Threading.Tasks.Task TestConnectionGetAsync() {
            return base.Channel.TestConnectionGetAsync();
        }
        
        public void TestConnectionPost() {
            base.Channel.TestConnectionPost();
        }
        
        public System.Threading.Tasks.Task TestConnectionPostAsync() {
            return base.Channel.TestConnectionPostAsync();
        }
        
        public System.Collections.Generic.List<InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.Act2> GetActs(string token, int versionNumber, int caseTypeId, string startDateString, string endDateString, string refNosString) {
            return base.Channel.GetActs(token, versionNumber, caseTypeId, startDateString, endDateString, refNosString);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.Act2>> GetActsAsync(string token, int versionNumber, int caseTypeId, string startDateString, string endDateString, string refNosString) {
            return base.Channel.GetActsAsync(token, versionNumber, caseTypeId, startDateString, endDateString, refNosString);
        }
        
        public void ExitAct(string token, int versionNumber, string caseReferenceId, string reason) {
            base.Channel.ExitAct(token, versionNumber, caseReferenceId, reason);
        }
        
        public System.Threading.Tasks.Task ExitActAsync(string token, int versionNumber, string caseReferenceId, string reason) {
            return base.Channel.ExitActAsync(token, versionNumber, caseReferenceId, reason);
        }
        
        public void Deposit(string token, int versionNumber, string caseReferenceId, InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.IncomingDeposit deposit1) {
            base.Channel.Deposit(token, versionNumber, caseReferenceId, deposit1);
        }
        
        public System.Threading.Tasks.Task DepositAsync(string token, int versionNumber, string caseReferenceId, InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.IncomingDeposit deposit) {
            return base.Channel.DepositAsync(token, versionNumber, caseReferenceId, deposit);
        }
        
        public System.Collections.Generic.List<InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.StatusUpdate> GetStatusUpdates(string token, string versionNumber) {
            return base.Channel.GetStatusUpdates(token, versionNumber);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.StatusUpdate>> GetStatusUpdatesAsync(string token, string versionNumber) {
            return base.Channel.GetStatusUpdatesAsync(token, versionNumber);
        }
        
        public void ImportActDirect(string token, int versionNumber, bool allDebtsBelongToAllDebtors, InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.Act actImport) {
            base.Channel.ImportActDirect(token, versionNumber, allDebtsBelongToAllDebtors, actImport);
        }
        
        public System.Threading.Tasks.Task ImportActDirectAsync(string token, int versionNumber, bool allDebtsBelongToAllDebtors, InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.Act actImport) {
            return base.Channel.ImportActDirectAsync(token, versionNumber, allDebtsBelongToAllDebtors, actImport);
        }
        
        public void UpdateAct(string token, int versionNumber, string caseReferenceId, bool allDebtsBelongToAllDebtors, InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.Debt debtImport) {
            base.Channel.UpdateAct(token, versionNumber, caseReferenceId, allDebtsBelongToAllDebtors, debtImport);
        }
        
        public System.Threading.Tasks.Task UpdateActAsync(string token, int versionNumber, string caseReferenceId, bool allDebtsBelongToAllDebtors, InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.Debt debtImport) {
            return base.Channel.UpdateActAsync(token, versionNumber, caseReferenceId, allDebtsBelongToAllDebtors, debtImport);
        }
        
        public void ImportAct(string token, int versionNumber, InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.Act actImport) {
            base.Channel.ImportAct(token, versionNumber, actImport);
        }
        
        public System.Threading.Tasks.Task ImportActAsync(string token, int versionNumber, InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.Act actImport) {
            return base.Channel.ImportActAsync(token, versionNumber, actImport);
        }
        
        public System.Collections.Generic.List<InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.PaymentSpecificationItem> GetPaymentSpecification(string token, string versionNumber, string startTimeString, string endTimeString) {
            return base.Channel.GetPaymentSpecification(token, versionNumber, startTimeString, endTimeString);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.PaymentSpecificationItem>> GetPaymentSpecificationAsync(string token, string versionNumber, string startTimeString, string endTimeString) {
            return base.Channel.GetPaymentSpecificationAsync(token, versionNumber, startTimeString, endTimeString);
        }
        
        public void EndSupply(string token, int versionNumber, string caseReferenceId, string action, string reason) {
            base.Channel.EndSupply(token, versionNumber, caseReferenceId, action, reason);
        }
        
        public System.Threading.Tasks.Task EndSupplyAsync(string token, int versionNumber, string caseReferenceId, string action, string reason) {
            return base.Channel.EndSupplyAsync(token, versionNumber, caseReferenceId, action, reason);
        }
        
        public System.Collections.Generic.List<InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.ExitReport> GetExitReport(string token, int versionNumber, int caseTypeId, string startTimeString, string endTimeString) {
            return base.Channel.GetExitReport(token, versionNumber, caseTypeId, startTimeString, endTimeString);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.ExitReport>> GetExitReportAsync(string token, int versionNumber, int caseTypeId, string startTimeString, string endTimeString) {
            return base.Channel.GetExitReportAsync(token, versionNumber, caseTypeId, startTimeString, endTimeString);
        }
        
        public System.Collections.Generic.List<InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.PaymentPlanItem> CreatePaymentPlan(string token, int versionNumber, int actId, int debtorId, string startTimeString, string amountString, string debtIdsString) {
            return base.Channel.CreatePaymentPlan(token, versionNumber, actId, debtorId, startTimeString, amountString, debtIdsString);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.PaymentPlanItem>> CreatePaymentPlanAsync(string token, int versionNumber, int actId, int debtorId, string startTimeString, string amountString, string debtIdsString) {
            return base.Channel.CreatePaymentPlanAsync(token, versionNumber, actId, debtorId, startTimeString, amountString, debtIdsString);
        }
        
        public int IsNotificationStoredProceduresStillRunning() {
            return base.Channel.IsNotificationStoredProceduresStillRunning();
        }
        
        public System.Threading.Tasks.Task<int> IsNotificationStoredProceduresStillRunningAsync() {
            return base.Channel.IsNotificationStoredProceduresStillRunningAsync();
        }
        
        public System.Collections.Generic.List<InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.UserAction> GetActionsToday() {
            return base.Channel.GetActionsToday();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<InkassoMaeglerenAPIDemoNETFramework.SystemOneSoapService.UserAction>> GetActionsTodayAsync() {
            return base.Channel.GetActionsTodayAsync();
        }
        
        public string GetWNSChannelToken() {
            return base.Channel.GetWNSChannelToken();
        }
        
        public System.Threading.Tasks.Task<string> GetWNSChannelTokenAsync() {
            return base.Channel.GetWNSChannelTokenAsync();
        }
        
        public void SetWNSChannelToken(string token) {
            base.Channel.SetWNSChannelToken(token);
        }
        
        public System.Threading.Tasks.Task SetWNSChannelTokenAsync(string token) {
            return base.Channel.SetWNSChannelTokenAsync(token);
        }
    }
}
