//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemOneService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Act2", Namespace="http://schemas.datacontract.org/2004/07/MainAPIWCF")]
    public partial class Act2 : object
    {
        
        private string CaseTypeField;
        
        private string CreditorField;
        
        private string ExitDateField;
        
        private string ExitReasonField;
        
        private string ImportDateStringField;
        
        private string RefNoField;
        
        private string StatusField;
        
        private System.Collections.Generic.List<SystemOneService.Deposit> depositsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CaseType
        {
            get
            {
                return this.CaseTypeField;
            }
            set
            {
                this.CaseTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Creditor
        {
            get
            {
                return this.CreditorField;
            }
            set
            {
                this.CreditorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExitDate
        {
            get
            {
                return this.ExitDateField;
            }
            set
            {
                this.ExitDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExitReason
        {
            get
            {
                return this.ExitReasonField;
            }
            set
            {
                this.ExitReasonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ImportDateString
        {
            get
            {
                return this.ImportDateStringField;
            }
            set
            {
                this.ImportDateStringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RefNo
        {
            get
            {
                return this.RefNoField;
            }
            set
            {
                this.RefNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SystemOneService.Deposit> deposits
        {
            get
            {
                return this.depositsField;
            }
            set
            {
                this.depositsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Deposit", Namespace="http://schemas.datacontract.org/2004/07/MainAPIWCF")]
    public partial class Deposit : object
    {
        
        private string DepositDateField;
        
        private int DepositIdField;
        
        private decimal DepositedAmountField;
        
        private string ImportDateField;
        
        private System.Collections.Generic.List<SystemOneService.CostDeposit> costDepositsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DepositDate
        {
            get
            {
                return this.DepositDateField;
            }
            set
            {
                this.DepositDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DepositId
        {
            get
            {
                return this.DepositIdField;
            }
            set
            {
                this.DepositIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal DepositedAmount
        {
            get
            {
                return this.DepositedAmountField;
            }
            set
            {
                this.DepositedAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ImportDate
        {
            get
            {
                return this.ImportDateField;
            }
            set
            {
                this.ImportDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SystemOneService.CostDeposit> costDeposits
        {
            get
            {
                return this.costDepositsField;
            }
            set
            {
                this.costDepositsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CostDeposit", Namespace="http://schemas.datacontract.org/2004/07/MainAPIWCF")]
    public partial class CostDeposit : object
    {
        
        private decimal AmountToClientField;
        
        private decimal AmountToDebtCollectorField;
        
        private int CostTypeIdField;
        
        private string CostTypeNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal AmountToClient
        {
            get
            {
                return this.AmountToClientField;
            }
            set
            {
                this.AmountToClientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal AmountToDebtCollector
        {
            get
            {
                return this.AmountToDebtCollectorField;
            }
            set
            {
                this.AmountToDebtCollectorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CostTypeId
        {
            get
            {
                return this.CostTypeIdField;
            }
            set
            {
                this.CostTypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CostTypeName
        {
            get
            {
                return this.CostTypeNameField;
            }
            set
            {
                this.CostTypeNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IncomingDeposit", Namespace="http://schemas.datacontract.org/2004/07/MainAPIWCF")]
    public partial class IncomingDeposit : object
    {
        
        private decimal AmountField;
        
        private string DebtorNameField;
        
        private string DepositDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DebtorName
        {
            get
            {
                return this.DebtorNameField;
            }
            set
            {
                this.DebtorNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DepositDate
        {
            get
            {
                return this.DepositDateField;
            }
            set
            {
                this.DepositDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusUpdate", Namespace="http://schemas.datacontract.org/2004/07/MainAPIWCF")]
    public partial class StatusUpdate : object
    {
        
        private int CaseTypeIdField;
        
        private int IdField;
        
        private string NewStatusField;
        
        private string RefNoField;
        
        private string TimestampField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CaseTypeId
        {
            get
            {
                return this.CaseTypeIdField;
            }
            set
            {
                this.CaseTypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewStatus
        {
            get
            {
                return this.NewStatusField;
            }
            set
            {
                this.NewStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RefNo
        {
            get
            {
                return this.RefNoField;
            }
            set
            {
                this.RefNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Timestamp
        {
            get
            {
                return this.TimestampField;
            }
            set
            {
                this.TimestampField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Act", Namespace="http://schemas.datacontract.org/2004/07/DBTool")]
    public partial class Act : object
    {
        
        private string caseOriginalCreditorField;
        
        private string caseReferenceIdField;
        
        private int caseTypeIdField;
        
        private System.Collections.Generic.List<SystemOneService.Debtor> debtorsField;
        
        private System.Collections.Generic.List<SystemOneService.Debt> debtsField;
        
        private System.Nullable<int> decisionField;
        
        private SystemOneService.ActExtraFields extraFieldsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string caseOriginalCreditor
        {
            get
            {
                return this.caseOriginalCreditorField;
            }
            set
            {
                this.caseOriginalCreditorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string caseReferenceId
        {
            get
            {
                return this.caseReferenceIdField;
            }
            set
            {
                this.caseReferenceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int caseTypeId
        {
            get
            {
                return this.caseTypeIdField;
            }
            set
            {
                this.caseTypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SystemOneService.Debtor> debtors
        {
            get
            {
                return this.debtorsField;
            }
            set
            {
                this.debtorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SystemOneService.Debt> debts
        {
            get
            {
                return this.debtsField;
            }
            set
            {
                this.debtsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> decision
        {
            get
            {
                return this.decisionField;
            }
            set
            {
                this.decisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SystemOneService.ActExtraFields extraFields
        {
            get
            {
                return this.extraFieldsField;
            }
            set
            {
                this.extraFieldsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActExtraFields", Namespace="http://schemas.datacontract.org/2004/07/DBTool")]
    public partial class ActExtraFields : object
    {
        
        private System.Collections.Generic.Dictionary<string, string> ExtraFieldsField;
        
        private System.Collections.Generic.Dictionary<string, string> ExtraFieldsDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> ExtraFields
        {
            get
            {
                return this.ExtraFieldsField;
            }
            set
            {
                this.ExtraFieldsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> ExtraFieldsData
        {
            get
            {
                return this.ExtraFieldsDataField;
            }
            set
            {
                this.ExtraFieldsDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Debtor", Namespace="http://schemas.datacontract.org/2004/07/DBTool")]
    public partial class Debtor : object
    {
        
        private string addressField;
        
        private string attentionField;
        
        private string birthdayField;
        
        private string cityField;
        
        private string coAddressField;
        
        private string countryCodeField;
        
        private string cprField;
        
        private string cvrField;
        
        private string emailField;
        
        private string nameField;
        
        private string phoneField;
        
        private string postalCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string attention
        {
            get
            {
                return this.attentionField;
            }
            set
            {
                this.attentionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string birthday
        {
            get
            {
                return this.birthdayField;
            }
            set
            {
                this.birthdayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string coAddress
        {
            get
            {
                return this.coAddressField;
            }
            set
            {
                this.coAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string countryCode
        {
            get
            {
                return this.countryCodeField;
            }
            set
            {
                this.countryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cpr
        {
            get
            {
                return this.cprField;
            }
            set
            {
                this.cprField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cvr
        {
            get
            {
                return this.cvrField;
            }
            set
            {
                this.cvrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string postalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Debt", Namespace="http://schemas.datacontract.org/2004/07/DBTool")]
    public partial class Debt : object
    {
        
        private System.Nullable<decimal> compensationFeeField;
        
        private string dueDateField;
        
        private SystemOneService.DebtExtraFields extraFieldsField;
        
        private System.Nullable<decimal> feeField;
        
        private System.Nullable<decimal> interestRateField;
        
        private string interestStartDateField;
        
        private string invoiceDateField;
        
        private string invoiceIdField;
        
        private System.Nullable<decimal> otherFeesField;
        
        private decimal principalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> compensationFee
        {
            get
            {
                return this.compensationFeeField;
            }
            set
            {
                this.compensationFeeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dueDate
        {
            get
            {
                return this.dueDateField;
            }
            set
            {
                this.dueDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SystemOneService.DebtExtraFields extraFields
        {
            get
            {
                return this.extraFieldsField;
            }
            set
            {
                this.extraFieldsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> fee
        {
            get
            {
                return this.feeField;
            }
            set
            {
                this.feeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> interestRate
        {
            get
            {
                return this.interestRateField;
            }
            set
            {
                this.interestRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string interestStartDate
        {
            get
            {
                return this.interestStartDateField;
            }
            set
            {
                this.interestStartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string invoiceDate
        {
            get
            {
                return this.invoiceDateField;
            }
            set
            {
                this.invoiceDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string invoiceId
        {
            get
            {
                return this.invoiceIdField;
            }
            set
            {
                this.invoiceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> otherFees
        {
            get
            {
                return this.otherFeesField;
            }
            set
            {
                this.otherFeesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal principal
        {
            get
            {
                return this.principalField;
            }
            set
            {
                this.principalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DebtExtraFields", Namespace="http://schemas.datacontract.org/2004/07/DBTool")]
    public partial class DebtExtraFields : object
    {
        
        private System.Collections.Generic.Dictionary<string, string> ExtraFieldsField;
        
        private System.Collections.Generic.Dictionary<string, string> ExtraFieldsDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> ExtraFields
        {
            get
            {
                return this.ExtraFieldsField;
            }
            set
            {
                this.ExtraFieldsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> ExtraFieldsData
        {
            get
            {
                return this.ExtraFieldsDataField;
            }
            set
            {
                this.ExtraFieldsDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentSpecificationItem", Namespace="http://schemas.datacontract.org/2004/07/MainAPIWCF")]
    public partial class PaymentSpecificationItem : object
    {
        
        private decimal AmountField;
        
        private string CaseTypeField;
        
        private string CostField;
        
        private string DepositDateField;
        
        private int DepositIdField;
        
        private string ImportTimeField;
        
        private string RefNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CaseType
        {
            get
            {
                return this.CaseTypeField;
            }
            set
            {
                this.CaseTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Cost
        {
            get
            {
                return this.CostField;
            }
            set
            {
                this.CostField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DepositDate
        {
            get
            {
                return this.DepositDateField;
            }
            set
            {
                this.DepositDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DepositId
        {
            get
            {
                return this.DepositIdField;
            }
            set
            {
                this.DepositIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ImportTime
        {
            get
            {
                return this.ImportTimeField;
            }
            set
            {
                this.ImportTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RefNo
        {
            get
            {
                return this.RefNoField;
            }
            set
            {
                this.RefNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExitReport", Namespace="http://schemas.datacontract.org/2004/07/MainAPIWCF")]
    public partial class ExitReport : object
    {
        
        private int ActIdField;
        
        private string CaseTypeField;
        
        private string CreditorField;
        
        private int CreditorIdField;
        
        private string ExitField;
        
        private string ExitTimeField;
        
        private string ExitTimeStringField;
        
        private System.DateTime ImportDateField;
        
        private string ImportDateStringField;
        
        private string PaidToField;
        
        private string RefNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ActId
        {
            get
            {
                return this.ActIdField;
            }
            set
            {
                this.ActIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CaseType
        {
            get
            {
                return this.CaseTypeField;
            }
            set
            {
                this.CaseTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Creditor
        {
            get
            {
                return this.CreditorField;
            }
            set
            {
                this.CreditorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CreditorId
        {
            get
            {
                return this.CreditorIdField;
            }
            set
            {
                this.CreditorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Exit
        {
            get
            {
                return this.ExitField;
            }
            set
            {
                this.ExitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExitTime
        {
            get
            {
                return this.ExitTimeField;
            }
            set
            {
                this.ExitTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExitTimeString
        {
            get
            {
                return this.ExitTimeStringField;
            }
            set
            {
                this.ExitTimeStringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime ImportDate
        {
            get
            {
                return this.ImportDateField;
            }
            set
            {
                this.ImportDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ImportDateString
        {
            get
            {
                return this.ImportDateStringField;
            }
            set
            {
                this.ImportDateStringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaidTo
        {
            get
            {
                return this.PaidToField;
            }
            set
            {
                this.PaidToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RefNo
        {
            get
            {
                return this.RefNoField;
            }
            set
            {
                this.RefNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentPlanItem", Namespace="http://schemas.datacontract.org/2004/07/MainAPIWCF")]
    public partial class PaymentPlanItem : object
    {
        
        private decimal AmountField;
        
        private string DateField;
        
        private decimal InterestField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Interest
        {
            get
            {
                return this.InterestField;
            }
            set
            {
                this.InterestField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAction", Namespace="http://schemas.datacontract.org/2004/07/MainAPIWCF")]
    public partial class UserAction : object
    {
        
        private int ActionIdField;
        
        private int UserIdField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActionId
        {
            get
            {
                return this.ActionIdField;
            }
            set
            {
                this.ActionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SystemOneService.SystemOneSoapService")]
    public interface SystemOneSoapService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/TestConnectionGet", ReplyAction="http://tempuri.org/SystemOneSoapService/TestConnectionGetResponse")]
        System.Threading.Tasks.Task TestConnectionGetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/TestConnectionPost", ReplyAction="http://tempuri.org/SystemOneSoapService/TestConnectionPostResponse")]
        System.Threading.Tasks.Task TestConnectionPostAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/GetActs", ReplyAction="http://tempuri.org/SystemOneSoapService/GetActsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SystemOneService.Act2>> GetActsAsync(string token, int versionNumber, int caseTypeId, string startDateString, string endDateString, string refNosString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/ExitAct", ReplyAction="http://tempuri.org/SystemOneSoapService/ExitActResponse")]
        System.Threading.Tasks.Task ExitActAsync(string token, int versionNumber, string caseReferenceId, string reason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/Deposit", ReplyAction="http://tempuri.org/SystemOneSoapService/DepositResponse")]
        System.Threading.Tasks.Task DepositAsync(string token, int versionNumber, string caseReferenceId, SystemOneService.IncomingDeposit deposit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/GetStatusUpdates", ReplyAction="http://tempuri.org/SystemOneSoapService/GetStatusUpdatesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SystemOneService.StatusUpdate>> GetStatusUpdatesAsync(string token, string versionNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/ImportActDirect", ReplyAction="http://tempuri.org/SystemOneSoapService/ImportActDirectResponse")]
        System.Threading.Tasks.Task ImportActDirectAsync(string token, int versionNumber, bool allDebtsBelongToAllDebtors, SystemOneService.Act actImport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/UpdateAct", ReplyAction="http://tempuri.org/SystemOneSoapService/UpdateActResponse")]
        System.Threading.Tasks.Task UpdateActAsync(string token, int versionNumber, string caseReferenceId, bool allDebtsBelongToAllDebtors, SystemOneService.Debt debtImport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/ImportAct", ReplyAction="http://tempuri.org/SystemOneSoapService/ImportActResponse")]
        System.Threading.Tasks.Task ImportActAsync(string token, int versionNumber, SystemOneService.Act actImport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/GetPaymentSpecification", ReplyAction="http://tempuri.org/SystemOneSoapService/GetPaymentSpecificationResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SystemOneService.PaymentSpecificationItem>> GetPaymentSpecificationAsync(string token, string versionNumber, string startTimeString, string endTimeString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/EndSupply", ReplyAction="http://tempuri.org/SystemOneSoapService/EndSupplyResponse")]
        System.Threading.Tasks.Task EndSupplyAsync(string token, int versionNumber, string caseReferenceId, string action, string reason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/GetExitReport", ReplyAction="http://tempuri.org/SystemOneSoapService/GetExitReportResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SystemOneService.ExitReport>> GetExitReportAsync(string token, int versionNumber, int caseTypeId, string startTimeString, string endTimeString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/CreatePaymentPlan", ReplyAction="http://tempuri.org/SystemOneSoapService/CreatePaymentPlanResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SystemOneService.PaymentPlanItem>> CreatePaymentPlanAsync(string token, int versionNumber, int actId, int debtorId, string startTimeString, string amountString, string debtIdsString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/IsNotificationStoredProceduresStillRunnin" +
            "g", ReplyAction="http://tempuri.org/SystemOneSoapService/IsNotificationStoredProceduresStillRunnin" +
            "gResponse")]
        System.Threading.Tasks.Task<int> IsNotificationStoredProceduresStillRunningAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/GetActionsToday", ReplyAction="http://tempuri.org/SystemOneSoapService/GetActionsTodayResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SystemOneService.UserAction>> GetActionsTodayAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/GetWNSChannelToken", ReplyAction="http://tempuri.org/SystemOneSoapService/GetWNSChannelTokenResponse")]
        System.Threading.Tasks.Task<string> GetWNSChannelTokenAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SystemOneSoapService/SetWNSChannelToken", ReplyAction="http://tempuri.org/SystemOneSoapService/SetWNSChannelTokenResponse")]
        System.Threading.Tasks.Task SetWNSChannelTokenAsync(string token);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface SystemOneSoapServiceChannel : SystemOneService.SystemOneSoapService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class SystemOneSoapServiceClient : System.ServiceModel.ClientBase<SystemOneService.SystemOneSoapService>, SystemOneService.SystemOneSoapService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SystemOneSoapServiceClient() : 
                base(SystemOneSoapServiceClient.GetDefaultBinding(), SystemOneSoapServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpsBinding_SystemOneSoapService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SystemOneSoapServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(SystemOneSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), SystemOneSoapServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SystemOneSoapServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SystemOneSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SystemOneSoapServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SystemOneSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SystemOneSoapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task TestConnectionGetAsync()
        {
            return base.Channel.TestConnectionGetAsync();
        }
        
        public System.Threading.Tasks.Task TestConnectionPostAsync()
        {
            return base.Channel.TestConnectionPostAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SystemOneService.Act2>> GetActsAsync(string token, int versionNumber, int caseTypeId, string startDateString, string endDateString, string refNosString)
        {
            return base.Channel.GetActsAsync(token, versionNumber, caseTypeId, startDateString, endDateString, refNosString);
        }
        
        public System.Threading.Tasks.Task ExitActAsync(string token, int versionNumber, string caseReferenceId, string reason)
        {
            return base.Channel.ExitActAsync(token, versionNumber, caseReferenceId, reason);
        }
        
        public System.Threading.Tasks.Task DepositAsync(string token, int versionNumber, string caseReferenceId, SystemOneService.IncomingDeposit deposit)
        {
            return base.Channel.DepositAsync(token, versionNumber, caseReferenceId, deposit);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SystemOneService.StatusUpdate>> GetStatusUpdatesAsync(string token, string versionNumber)
        {
            return base.Channel.GetStatusUpdatesAsync(token, versionNumber);
        }
        
        public System.Threading.Tasks.Task ImportActDirectAsync(string token, int versionNumber, bool allDebtsBelongToAllDebtors, SystemOneService.Act actImport)
        {
            return base.Channel.ImportActDirectAsync(token, versionNumber, allDebtsBelongToAllDebtors, actImport);
        }
        
        public System.Threading.Tasks.Task UpdateActAsync(string token, int versionNumber, string caseReferenceId, bool allDebtsBelongToAllDebtors, SystemOneService.Debt debtImport)
        {
            return base.Channel.UpdateActAsync(token, versionNumber, caseReferenceId, allDebtsBelongToAllDebtors, debtImport);
        }
        
        public System.Threading.Tasks.Task ImportActAsync(string token, int versionNumber, SystemOneService.Act actImport)
        {
            return base.Channel.ImportActAsync(token, versionNumber, actImport);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SystemOneService.PaymentSpecificationItem>> GetPaymentSpecificationAsync(string token, string versionNumber, string startTimeString, string endTimeString)
        {
            return base.Channel.GetPaymentSpecificationAsync(token, versionNumber, startTimeString, endTimeString);
        }
        
        public System.Threading.Tasks.Task EndSupplyAsync(string token, int versionNumber, string caseReferenceId, string action, string reason)
        {
            return base.Channel.EndSupplyAsync(token, versionNumber, caseReferenceId, action, reason);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SystemOneService.ExitReport>> GetExitReportAsync(string token, int versionNumber, int caseTypeId, string startTimeString, string endTimeString)
        {
            return base.Channel.GetExitReportAsync(token, versionNumber, caseTypeId, startTimeString, endTimeString);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SystemOneService.PaymentPlanItem>> CreatePaymentPlanAsync(string token, int versionNumber, int actId, int debtorId, string startTimeString, string amountString, string debtIdsString)
        {
            return base.Channel.CreatePaymentPlanAsync(token, versionNumber, actId, debtorId, startTimeString, amountString, debtIdsString);
        }
        
        public System.Threading.Tasks.Task<int> IsNotificationStoredProceduresStillRunningAsync()
        {
            return base.Channel.IsNotificationStoredProceduresStillRunningAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SystemOneService.UserAction>> GetActionsTodayAsync()
        {
            return base.Channel.GetActionsTodayAsync();
        }
        
        public System.Threading.Tasks.Task<string> GetWNSChannelTokenAsync()
        {
            return base.Channel.GetWNSChannelTokenAsync();
        }
        
        public System.Threading.Tasks.Task SetWNSChannelTokenAsync(string token)
        {
            return base.Channel.SetWNSChannelTokenAsync(token);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_SystemOneSoapService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_SystemOneSoapService))
            {
                return new System.ServiceModel.EndpointAddress("https://inkassomaeglerenwcfapidevelop.azurewebsites.net/SystemOneSoapService.svc/" +
                        "soap");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SystemOneSoapServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpsBinding_SystemOneSoapService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SystemOneSoapServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpsBinding_SystemOneSoapService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpsBinding_SystemOneSoapService,
        }
    }
}
